version: "3.9"

services:
  api:
    image: node:24-alpine
    working_dir: /app
    env_file:
      - ./.env.local
      - ./api/.env.example
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules
    command: sh -c "npm i && npm run dev"
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  web:
    image: node:24-alpine
    working_dir: /app
    env_file:
      - ./.env.local
      - ./web/.env.example
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    command: sh -c "npm i && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"

  n8n:
    image: n8nio/n8n:latest
    env_file:
      - ./n8n/.env.example
    environment:
      - N8N_DIAGNOSTICS_ENABLED=false
    volumes:
      - ./.data/n8n:/home/node/.n8n
    ports:
      - "5678:5678"
    # healthcheck optional; n8n takes a bit to boot

volumes:
  api_node_modules:
  web_node_modules:
